# Prometheus Configuration for NSE Stock Analysis Bot

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'nse-bot-production'
    service: 'stock-analysis-bot'

# Alertmanager configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           - alertmanager:9093

# Rule files (for alerting rules)
rule_files:
  - "alert_rules.yml"

# Scrape configurations
scrape_configs:
  # NSE Bot Application
  - job_name: 'nse-bot-app'
    static_configs:
      - targets: ['nse-bot:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    
  # PostgreSQL Database (requires postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    
  # Redis Cache (requires redis_exporter)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s
    
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 30d
    retention.size: 10GB